### PR TITLE
Fix build error with cordova ios@4.0.x

### PR DESCRIPTION
**Pull request by ace68723**

### CODE REVIEW

**Comment by coderroggie** [comment]
This appears to fix the issues that I was having with building with cordova-ios-4.x as well.  

+1

**Comment by eweap** [comment]
Yes, I confirm this PR fix the issues with building with cordova-ios-4.x with the ionic delpoy plugin ! Thanks @ace68723

+1

**Comment by robincrorie** [comment]
Bump :) :+1:

**Comment by craigvl** [comment]
Yes I am also getting the error

`error: no visible @interface for 'UIView' declares the selector 'loadRequest:'
        [self.webView loadRequest: [NSURLRequest requestWithURL:components.URL] ];`

After updating to the latest cordova version and then try and build ios.

**Comment by poychang** [comment]
I get the same error and fix with this. Thanks @ace68723.

**Comment by HenrySipp** [comment]
+1 this solved my problems.

**Comment by EduardMalik** [comment]
Now it's work. Thanks @ace68723.
+1

**Comment by Telemakhos** [comment]
@ericb Could you merge this? one co-worked just faced this issue and we've been like 3 hours debugging the build fail until we found this patch...

Thanks!

**Comment by ArjenBroeze** [comment]
New to this github stuff. How do I add this fix to my project?

**Comment by Telemakhos** [comment]
Just use ace68723 fork in the mean time...
```
$ ionic plugin remove ionic-plugin-deploy
$ ionic plugin add https://github.com/ace68723/ionic-plugin-deploy
```

When the patch makes it to ionic-plugin-deploy switch back...

**Comment by ArjenBroeze** [comment]
Thanks!

**Comment by jsolano** [comment]
Thank you!... safe my day....

**Comment by joelbowen** [comment]
+1Million. Please accept this PR, yesterday.

**Comment by ericb** [comment]
This has been merged and publish as part of the 0.5.0 release. Thanks @ace68723

**Pull request closed without merging**
